# https://www.playframework.com/documentation/latest/Configuration

play.http.errorHandler = "config.ErrorHandler"
play.http.secret.key = ${?APP_SECRET}
http.port = 9234
play.http.session.secure = false
play.http.session.secure = ${?IS_SESSION_SECURE}

play.i18n.langs = [ "en" ]

allowedHost = "localhost:"${http.port}
allowedHost = ${?PLAY_FILTERS_HOSTS}
protocol = "http://"
protocol = ${?PROTOCOL}
appName = "uk-fuel-prices"

play.filters.enabled += "filters.SessionFilter"
play.filters.enabled += "filters.RequestAttrFilter"

play.filters.hosts {
  allowed = [${allowedHost}]
}
play.filters.headers {
  frameOptions = "SAMEORIGIN"
}

play.modules.enabled += "config.AppModules"
play.modules.enabled += "config.JobSchedulerModule"

play.server.pidfile.path=/dev/null

database.name=fuel_price
db.default.driver=org.mariadb.jdbc.Driver
db.default.url="jdbc:mariadb://localhost:3306/"${database.name}"?createDatabaseIfNotExist=true"
db.default.url=${?DB_URL}
db.default.username=root
db.default.username=${?DB_USER}
db.default.password=example
db.default.password=${?DB_PASSWORD}
db.default.logSql=true


database.dispatcher {
  thread-pool-executor {
    core-pool-size-factor = 10.0
    core-pool-size-max = 10
  }
}

scheduler {
  partial-update {
    isEnabled = false
    isEnabled = ${?PARTIAL_UPDATE_IS_ENABLED}
    jobIntervalInMinutes = 5
    jobIntervalInMinutes = ${?PARTIAL_UPDATE_JOB_INTERVAL_IN_MINUTES}
    startDelayInSeconds = 120
    startDelayInSeconds = ${?PARTIAL_UPDATE_START_DELAY_IN_SECONDS}
    schedulerIntervalInMinutes = 1
    schedulerIntervalInMinutes = ${?PARTIAL_UPDATE_SCHEDULER_INTERVAL_IN_MINUTES}
  }
  full-update {
    isEnabled = false
    isEnabled = ${?FULL_UPDATE_IS_ENABLED}
    schedulerIntervalInMinutes = 13
    schedulerIntervalInMinutes = ${?FULL_UPDATE_SCHEDULER_INTERVAL_IN_MINUTES}
    startDelayInSeconds = 10
    startDelayInSeconds = ${?FULL_UPDATE_START_DELAY_IN_SECONDS}
  }
}


microservice {
  services {
    fuel-finder {
        host = www.fuel-finder.service.gov.uk
        host = ${?FUEL_HOST}
        port = 443
        port = ${?FUEL_PORT}
        protocol = https
        protocol = ${?FUEL_PROTOCOL}
        client-id = "DUMMY_CLIENT_ID"
        client-id = ${?FUEL_CLIENT_ID}
        client-secret = "DUMMY_SECRET_ID"
        client-secret = ${?FUEL_CLIENT_SECRET}
    }
  }
}